[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
reqwest = { version = "0.12.12", features = ["blocking"] }
serde_json = "1.0.135"
